apidoc:
  title: 联想丝路数据对接
  version: 0.0.1
  treenode: [通用,外观全景,楼宇设备,信息设施]
  content: | # 接口文档的基础结构
    @@@
    ### 接口描述
    {0}

    ### 可传参数
    | 参数名 | 是否必传 | 数据类型 | 参数说明 |
    |--|--|--|--|
    {1}

    ### 请求样例
    ```cmd
      http:127.0.0.1:5000/{2}
    ```

    ### 返回样例
    ```json
      {{"code": 0, "msg": "成功", "data": {3}}}
    ```

    {4}
    @@@
  extradescr: | # 额外说明
    ### 额外说明

    >**当前接口不代表最终效果，随着细节的对接，接口的参数和url可能变化**
  
  args: # 请求的通用参数
    area: area|false|str|区域 \n
    prof: profession|false|str|专业 \n
    dev: dev| false | str |设备 \n
    page: | 
      pageindex|false | int  | 数据页数
      pageSize |false | int  | 每页数量 
    none:  |
      |- | - | - | - 
  
  # 以蓝图为名称，配制各个接口的文档
  method:
    mapinfo:
      descr:  # 接口描述
      args: [] # 可以在args里面定义然后写在这里
      ownargs:  # 自己独有的请求参数
      req: 
      resp: 



    
